config/routes.rb
SampleApp::Application.routes.draw do

  match '/signup', :to => 'users#new'

  root :to => 'pages#home'
  
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/test', :to => 'pages#test'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li>
				<%= link_to "About", about_path %>
			</li>
			<li>
				<%= link_to "Contact", contact_path %>
			</li>
			<li>
				<%= link_to "News", 'http://news.railstutorial.org' %>
			</li>
			<li>
				<%= link_to "Rails Tutorial", 'http://railstutorial.org' %>
			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li>
				<%= link_to "Home", root_path %>
			</li>
			<% if signed_in? %>
				<li>
					<%= link_to "Profile", current_user %>
				</li>
				<li>
					<%= link_to "Users", users_path %>
				</li>
				<li>
					<%= link_to "Settings", edit_user_path(current_user) %>
				</li>
			<% end %>
			<li>
				<%= link_to "Help", help_path %>
			</li>
			<% if signed_in? %>
				<li>
					<%= link_to "Sign out", signout_path %>
				</li>
			<% else %>
				<li>
					<%= link_to "Sign in", signin_path %>
				</li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Ruby on Rails Tutorial Sample App | <%= @title %></title>
		<%= render 'layouts/stylesheets' %>
	</head>
	<body>
		<div class="container">		
			<%= render 'layouts/header' %>
			<section class="round">
				<% flash.each do |key, value| %>
					<div class="flash <%= key %>"><%= value %></div>
				<% end %>
				<%= yield %>				
			</section>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>